# ===================================================================
# CONFIGURAÇÕES DO SERVIDOR
# ===================================================================
server.port=8080

# ===================================================================
# CONFIGURAÇÕES DO BANCO DE DADOS (H2 EM MEMÓRIA)
# ===================================================================
# IMPORTANTE: Força o Spring a ler o Driver e a URL explicitamente
spring.datasource.url=jdbc:h2:mem:eventosdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Define explicitamente o dialeto moderno para o H2 (evita o erro do log)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Cria e atualiza as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Exibe o SQL no terminal para acompanharmos
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# INTERFACE DO H2 CONSOLE
# ===================================================================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# ===================================================================
# CONFIGURAÇÕES DO THYMELEAF E API
# ===================================================================
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8


openweathermap.api.key=e9a0b5ac2aa6342f2bf5d3b39979e770
server.forward-headers-strategy=framework